import { Movie, Series, Genre } from "@/types/content";

export type DemoMovieItem = Movie & {
  posterUrl: string;
  backdropUrl: string;
  isBengali?: boolean;
  genresList?: string[];
};

export type DemoSeriesItem = Series & {
  posterUrl: string;
  backdropUrl: string;
  isBengali?: boolean;
  genresList?: string[];
};

export const DEMO_MOVIES: DemoMovieItem[] = [
  {
    id: "m1",
    title: "Surongo",
    title_bn: "সুরঙ্গ",
    slug: "surongo",
    description: "A gripping heist drama following Masud, an electrician whose desperation leads him to build a tunnel beneath a bank vault.",
    release_year: 2023,
    duration_minutes: 152,
    rating: 8.8,
    status: "published",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    original_title: null,
    description_bn: "মাসুদের দুঃসাহসিক ব্যাংক সুরঙ্গ ও নিঃস্ব জীবনসংগ্রামের রোমাঞ্চকর কাহিনী।",
    tagline: null,
    content_rating: "13+",
    media: {},
    search_keywords: "surongo, surung",
    published_at: "2026-01-01T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: true,
    is_trending: true,
    view_count: 1000,
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Crime", "Thriller", "Drama"],
  } as unknown as DemoMovieItem,
  {
    id: "m2",
    title: "Priyotoma",
    title_bn: "প্রিয়তমা",
    slug: "priyotoma",
    description: "An intense romantic action spectacle charting the tumultuous journey of love, loss, and vengeance.",
    release_year: 2023,
    duration_minutes: 145,
    rating: 8.5,
    status: "published",
    created_at: "2026-01-02T00:00:00Z",
    updated_at: "2026-01-02T00:00:00Z",
    original_title: null,
    description_bn: "ভালোবাসা, ট্র্যাজেডি এবং প্রতিশোধের এক অনবদ্য বাংলা রোমান্টিক থ্রিলার।",
    tagline: null,
    content_rating: "13+",
    media: {},
    search_keywords: "priyotoma",
    published_at: "2026-01-02T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: false,
    is_trending: true,
    view_count: 850,
    posterUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1518676599626-5cd8c2d3f853?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Action", "Romance", "Drama"],
  } as unknown as DemoMovieItem,
  {
    id: "m3",
    title: "Toofan",
    title_bn: "তুফান",
    slug: "toofan",
    description: "Rise of a nineties gangster who builds an empire against corrupt law enforcement and rival cartels.",
    release_year: 2024,
    duration_minutes: 160,
    rating: 9.1,
    status: "published",
    created_at: "2026-01-03T00:00:00Z",
    updated_at: "2026-01-03T00:00:00Z",
    original_title: null,
    description_bn: "৯০ দশকের অন্ধকার আন্ডারওয়ার্ল্ডের অধিপতি হয়ে ওঠার এক দুর্ধর্ষ অ্যাকশন গল্প।",
    tagline: null,
    content_rating: "16+",
    media: {},
    search_keywords: "toofan",
    published_at: "2026-01-03T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: true,
    is_trending: true,
    view_count: 1200,
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Action", "Crime"],
  } as unknown as DemoMovieItem,
  {
    id: "m4",
    title: "Hawa",
    title_bn: "হাওয়া",
    slug: "hawa",
    description: "A mysterious woman enters a deep-sea fishing trawler, unleashing ancient folklore and psychological dread.",
    release_year: 2022,
    duration_minutes: 131,
    rating: 8.9,
    status: "published",
    created_at: "2026-01-04T00:00:00Z",
    updated_at: "2026-01-04T00:00:00Z",
    original_title: null,
    description_bn: "মাঝদরিয়ায় ট্রলারে এক রহস্যময়ী নারীর আগমন এবং রূপকথার রোমাঞ্চকর রহস্য।",
    tagline: null,
    content_rating: "13+",
    media: {},
    search_keywords: "hawa",
    published_at: "2026-01-04T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: false,
    is_trending: true,
    view_count: 950,
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Mystery", "Drama"],
  } as unknown as DemoMovieItem,
  {
    id: "m5",
    title: "Dune: Part Two",
    title_bn: "ডিউন: পার্ট টু",
    slug: "dune-part-two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    release_year: 2024,
    duration_minutes: 166,
    rating: 8.7,
    status: "published",
    created_at: "2026-01-05T00:00:00Z",
    updated_at: "2026-01-05T00:00:00Z",
    original_title: null,
    description_bn: "পল আত্রেয়াদেস এবং ফ্রেমানদের মহাজাগতিক যুদ্ধ ও প্রতিশোধের মহাকাব্য।",
    tagline: null,
    content_rating: "PG-13",
    media: {},
    search_keywords: "dune",
    published_at: "2026-01-05T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: false,
    is_trending: true,
    view_count: 1100,
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop",
    isBengali: false,
    genresList: ["Sci-Fi", "Adventure"],
  } as unknown as DemoMovieItem,
  {
    id: "m6",
    title: "Oggatonama",
    title_bn: "অজ্ঞাতনামা",
    slug: "oggatonama",
    description: "An emotional social thriller exploring identity, human trafficking, and family sacrifice.",
    release_year: 2016,
    duration_minutes: 125,
    rating: 8.6,
    status: "published",
    created_at: "2026-01-06T00:00:00Z",
    updated_at: "2026-01-06T00:00:00Z",
    original_title: null,
    description_bn: null,
    tagline: null,
    content_rating: "PG",
    media: {},
    search_keywords: "oggatonama",
    published_at: "2026-01-06T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: false,
    is_trending: false,
    view_count: 700,
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Drama", "Thriller"],
  } as unknown as DemoMovieItem,
];

export const DEMO_SERIES: DemoSeriesItem[] = [
  {
    id: "s1",
    title: "Karaghar",
    title_bn: "কারাগার",
    slug: "karaghar",
    description: "Cell 145 has been locked for 50 years. Suddenly a prisoner appears inside claiming to be 250 years old.",
    release_year: 2022,
    rating: 9.3,
    status: "published",
    created_at: "2026-01-01T00:00:00Z",
    updated_at: "2026-01-01T00:00:00Z",
    original_title: null,
    description_bn: "৫০ বছর ধরে বন্ধ থাকা ১৪৫ নম্বর সেলে হঠাৎ এক রহস্যময় কয়েদির আবির্ভাব।",
    tagline: null,
    content_rating: "16+",
    media: {},
    search_keywords: "karaghar, karagar",
    published_at: "2026-01-01T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: true,
    is_trending: true,
    view_count: 1500,
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1518676599626-5cd8c2d3f853?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Mystery", "Sci-Fi", "Thriller"],
  } as unknown as DemoSeriesItem,
  {
    id: "s2",
    title: "Taqdeer",
    title_bn: "তকদীর",
    slug: "taqdeer",
    description: "A freezer van driver discovers an unidentified woman's corpse in his vehicle, pulling him into a web of conspiracy.",
    release_year: 2020,
    rating: 9.0,
    status: "published",
    created_at: "2026-01-02T00:00:00Z",
    updated_at: "2026-01-02T00:00:00Z",
    original_title: null,
    description_bn: "ফ্রিজার ভ্যান ড্রাইভার তকদীরের গাড়িতে বেওয়ারিশ লাশ ও রহস্যময় চক্রান্ত।",
    tagline: null,
    content_rating: "16+",
    media: {},
    search_keywords: "taqdeer",
    published_at: "2026-01-02T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: false,
    is_trending: true,
    view_count: 900,
    posterUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Crime", "Thriller"],
  } as unknown as DemoSeriesItem,
  {
    id: "s3",
    title: "Mohanagar",
    title_bn: "মহানগর",
    slug: "mohanagar",
    description: "One night inside a Dhaka police station reveals dark politics, corruption, and morals tested under pressure.",
    release_year: 2021,
    rating: 9.2,
    status: "published",
    created_at: "2026-01-03T00:00:00Z",
    updated_at: "2026-01-03T00:00:00Z",
    original_title: null,
    description_bn: "ঢাকার এক থানার এক রাতের গল্পে ক্ষমতা, দুর্নীতি ও বিবেকের অদ্ভুত লড়াই।",
    tagline: null,
    content_rating: "16+",
    media: {},
    search_keywords: "mohanagar",
    published_at: "2026-01-03T00:00:00Z",
    published_content_fts: null,
    original_language_id: null,
    country_id: null,
    trailer_url: null,
    seo_title: null,
    seo_description: null,
    seo_keywords: null,
    is_featured: false,
    is_trending: true,
    view_count: 1300,
    posterUrl: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop",
    backdropUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop",
    isBengali: true,
    genresList: ["Crime", "Drama"],
  } as unknown as DemoSeriesItem,
];

export const DEMO_GENRES: Genre[] = [
  { id: "g1", name: "Action", name_bn: "অ্যাকশন", slug: "action", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g2", name: "Thriller", name_bn: "থ্রিলার", slug: "thriller", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g3", name: "Drama", name_bn: "ড্রামা", slug: "drama", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g4", name: "Crime", name_bn: "ক্রাইম", slug: "crime", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g5", name: "Mystery", name_bn: "রহস্য", slug: "mystery", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g6", name: "Sci-Fi", name_bn: "সাই-ফাই", slug: "sci-fi", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g7", name: "Romance", name_bn: "রোমান্স", slug: "romance", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
  { id: "g8", name: "Comedy", name_bn: "কমেডি", slug: "comedy", description: null, created_at: "2026-01-01T00:00:00Z", updated_at: "2026-01-01T00:00:00Z" },
];
